/** MasterConfig.category 허용 값 */
export const MASTER_CONFIG_CATEGORIES = {
  BRAND: 'BRAND',
  STORE_STATUS: 'STORE_STATUS',
  REGION: 'REGION',
  SV_MANAGER: 'SV_MANAGER',
  BRANCH_TYPE: 'BRANCH_TYPE',
  MARKET_TYPE: 'MARKET_TYPE',
  TERMINATION_NOTICE_PERIOD: 'TERMINATION_NOTICE_PERIOD',
  POS_HW: 'POS_HW',
  POS_VENDOR: 'POS_VENDOR',
  SW_TYPE: 'SW_TYPE',
  TABLE_ORDER_VENDOR: 'TABLE_ORDER_VENDOR',
} as const;

export type MasterConfigCategory =
  (typeof MASTER_CONFIG_CATEGORIES)[keyof typeof MASTER_CONFIG_CATEGORIES];

export const MASTER_CONFIG_CATEGORY_LIST = Object.values(
  MASTER_CONFIG_CATEGORIES,
);

/** 가맹점 등록 폼 Select에 사용하는 category 목록 */
export const STORE_FORM_CONFIG_CATEGORIES = [
  MASTER_CONFIG_CATEGORIES.BRAND,
  MASTER_CONFIG_CATEGORIES.STORE_STATUS,
  MASTER_CONFIG_CATEGORIES.REGION,
  MASTER_CONFIG_CATEGORIES.SV_MANAGER,
  MASTER_CONFIG_CATEGORIES.BRANCH_TYPE,
  MASTER_CONFIG_CATEGORIES.MARKET_TYPE,
  MASTER_CONFIG_CATEGORIES.TERMINATION_NOTICE_PERIOD,
  MASTER_CONFIG_CATEGORIES.POS_HW,
  MASTER_CONFIG_CATEGORIES.SW_TYPE,
  MASTER_CONFIG_CATEGORIES.TABLE_ORDER_VENDOR,
] as const;

export const CATEGORY_LABELS: Record<MasterConfigCategory, string> = {
  BRAND: '브랜드',
  STORE_STATUS: '운영상태',
  REGION: '지자체',
  SV_MANAGER: '담당 SV',
  BRANCH_TYPE: '영업 형태',
  MARKET_TYPE: '상권유형',
  TERMINATION_NOTICE_PERIOD: '해지 통보 주기',
  POS_HW: 'POS H/W 업체',
  POS_VENDOR: 'POS 업체',
  SW_TYPE: 'POS S/W 종류',
  TABLE_ORDER_VENDOR: '테이블오더 업체',
};
